name: Commit on Issue #1 Update

on:
  issues:
    types: [opened, edited, closed]

jobs:
  commit-job:
    if: ${{ github.event.issue.number == 1 && github.event.issue.title == 'update' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create commit with Issue Body as Message
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          # Konfiguracja użytkownika dla commita
          git config user.name "coolxer"
          git config user.email "lukasz.milos.it@gmail.com"

          # Tworzenie "pustego" commita
          git commit --allow-empty -m "${ISSUE_BODY}"

          git push
